---
# Copyright (C) 2020 Stefan Haun
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (RaspiOS) Add Debian Backports repository for WireGuard
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_facts.lsb.codename }}-backports main"
    state: present
    update_cache: yes

- name: (RaspiOS) Install latest kernel
  apt:
    name:
    - "raspberrypi-kernel"
    state: latest
  register: wireguard__register_kernel_update

- name: (RaspiOS) Reboot after kernel update (Ansible >= 2.8)
  reboot:
    search_paths: ['/lib/molly-guard', '/usr/sbin', '/sbin']
  when:
    - ansible_version.full is version('2.8.0', '>=')
    - wireguard__register_kernel_update is changed

- name: (RaspiOS) Check if molly-guard is installed (Ansible < 2.8)
  stat:
    path: /lib/molly-guard/
  register: wireguard__register_molly_guard

- name: (RaspiOS) Reboot after kernel update (Ansible < 2.8, no molly-guard)
  reboot:
  when:
    - ansible_version.full is version('2.8.0', '<')
    - wireguard__register_kernel_update is changed
    - not wireguard__register_molly_guard.stat.exists

- name: (RaspiOS) Reboot after kernel update (Ansible < 2.8, with molly-guard)
  command: /lib/molly-guard/shutdown -r now
  async: 1
  poll: 0
  ignore_unreachable: yes
  when:
    - ansible_version.full is version('2.8.0', '<')
    - wireguard__register_kernel_update is changed
    - wireguard__register_molly_guard.stat.exists

- name: (RaspiOS) Waiting for host to be available (Ansible < 2.8, with molly-guard)
  wait_for_connection:
  when:
    - ansible_version.full is version('2.8.0', '<')
    - wireguard__register_kernel_update is changed
    - wireguard__register_molly_guard.stat.exists

- name: (RaspiOS) Install WireGuard packages
  apt:
    name:
      - "wireguard-tools"
    state: present
